# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
%define byaccdate 20111219
# << macros

Name:       byacc
Summary:    Berkeley Yacc, a parser generator
Version:    1.9.%{byaccdate}
Release:    1
Group:      Development/Tools
License:    Public Domain
URL:        http://invisible-island.net/byacc/byacc.html
Source0:    ftp://invisible-island.net/byacc/byacc-%{byaccdate}.tgz
Source100:  byacc.yaml


%description
Byacc (Berkeley Yacc) is a public domain LALR parser generator which
is used by many programs during their build process.

If you are going to do development on your system, you will want to install
this package.




%prep
%setup -q -n %{name}-%{byaccdate}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --disable-dependency-tracking

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
#make DESTDIR=$RPM_BUILD_ROOT install
ln -s yacc $RPM_BUILD_ROOT/%{_bindir}/byacc
ln -s yacc.1 $RPM_BUILD_ROOT/%{_mandir}/man1/byacc.1
# << install post
%check
# >> check
make check
# << check






%files
%defattr(-,root,root,-)
# >> files
%doc ACKNOWLEDGEMENTS CHANGES NEW_FEATURES NOTES NO_WARRANTY README
%{_bindir}/yacc
%{_bindir}/byacc
%{_mandir}/man1/yacc.1*
%{_mandir}/man1/byacc.1*
# << files


